cache:
  paths:
    - node_modules/
    - yarn.lock

stages:
  - test
  - publish

test:
  stage: test
  script:
    - "npm install"
    - "npm run lint"
    - "npm run test"
  tags:
    - node

npm:
  stage: publish
  script:
    - "npm publish"
  only:
    - master
  tags:
    - node
